sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt551-trusty
  - sudo apt-get update -qq
  - pip install --user cpp-coveralls

install:
  - sudo apt-get -y install qt55[QTPACKAGE]
  - git config --global color.ui false
  - sudo apt-get -y install python3-pip
  - sudo pip3 install gitpython

script:
  - sudo service influxdb start
  - sudo service influxdb status
  - echo "clone dependency repos"
  - repoURL="https://github.com/${TRAVIS_REPO_SLUG}.git"
  - branch=${TRAVIS_BRANCH}
  - manifest="default.xml"
  - git clone https://github.com/mezorian/EasyDepend.git
  - cp EasyDepend/*.py .
  - python3 example.py
  - ls -la
  - echo "start build"
  - source /opt/qt55/bin/qt55-env.sh
  - /opt/qt55/bin/qmake
  - make clean
  - make
  - ./DBInterface

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp' --exclude test/catch.hpp
